### ISSUE TITLE
manage_servers check

### ISSUE THREAD

**Issue by flaree** [Malarne/discord_cogs#21]
Cog won't load on r3.post1 as the check has been changed.

```Exception during loading of cog
Traceback (most recent call last):
  File "/home/flare/rewrite/lib/python3.7/site-packages/redbot/core/core_commands.py", line 104, in _load
    await bot.load_extension(spec)
  File "/home/flare/rewrite/lib/python3.7/site-packages/redbot/core/bot.py", line 233, in load_extension
    lib = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/flare/.local/share/Red-DiscordBot/cogs/CogManager/cogs/Boobs/__init__.py", line 1, in <module>
    from .oboobs import OboobsC
  File "/home/flare/.local/share/Red-DiscordBot/cogs/CogManager/cogs/Boobs/oboobs.py", line 31, in <module>
    class OboobsC(commands.Cog):
  File "/home/flare/.local/share/Red-DiscordBot/cogs/CogManager/cogs/Boobs/oboobs.py", line 104, in OboobsC
    @_oboobs.command(pass_context=True, no_pm=True)
  File "/home/flare/rewrite/lib/python3.7/site-packages/redbot/core/commands/requires.py", line 316, in decorator
    _validate_perms_dict(user_perms)
  File "/home/flare/rewrite/lib/python3.7/site-packages/redbot/core/commands/requires.py", line 703, in _validate_perms_dict
    raise TypeError(f"Unknown permission name '{perm}'")
TypeError: Unknown permission name 'manage_server'
```

**Comment by Malarne** [comment]
should be fixed on latest version, switched to administrator=True instead
