### ISSUE TITLE
leveler error when loading

### ISSUE THREAD

**Issue by moonlitopal** [Malarne/discord_cogs#32]
when i run [p]load leveler i get
i did install Pillow 5.3.0
`Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/redbot/lib/python3.7/site-packages/redbot/core/core_commands.py", line 106, in _load
    await bot.load_extension(spec)
  File "/home/pi/.pyenv/versions/redbot/lib/python3.7/site-packages/redbot/core/bot.py", line 302, in load_extension
    lib.setup(self)
  File "/home/pi/.local/share/Red-DiscordBot/cogs/CogManager/cogs/Leveler/__init__.py", line 7, in setup
    bot.add_cog(n)
  File "/home/pi/.pyenv/versions/redbot/lib/python3.7/site-packages/redbot/core/bot.py", line 429, in add_cog
    super().add_cog(cog)
  File "/home/pi/.pyenv/versions/redbot/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 482, in add_cog
    cog = cog._inject(self)
  File "/home/pi/.pyenv/versions/redbot/lib/python3.7/site-packages/discord/ext/commands/cog.py", line 378, in _inject
    bot.remove_command(to_undo)
  File "/home/pi/.pyenv/versions/redbot/lib/python3.7/site-packages/redbot/core/bot.py", line 464, in remove_command
    command.requires.reset()
AttributeError: 'NoneType' object has no attribute 'requires'`

**Comment by kennnyshiwa** [comment]
You have a cog with the same command look through your other cogs and unload the one with the conflicting command. Or there is more traceback above this that you can post that can help us find the command that is conflicting

**Comment by moonlitopal** [comment]
thats the only traceback i get
what are all the commands i can look through to figure it out?

**Comment by kennnyshiwa** [comment]
its most likely one of these 
register
toplevel
profile
levelerset

You can use the ``[p]findcog`` command to find if these commands are present

**Comment by moonlitopal** [comment]
its register i use that for setting roles anyway i can have both working?

**Comment by kennnyshiwa** [comment]
no

**Comment by moonlitopal** [comment]
i guess i will have to reconfigre that command for setting roles manually then thanks for the help
