### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by JamsRepos** [Malarne/discord_cogs#34]
Upon running !profile now, I'm seeming to get an error. Happened after I decided to release the feature to my discord.

```4|NexusBot  | [2019-10-28 12:09:01] [ERROR] red: Exception in command 'profile'
4|NexusBot  | Traceback (most recent call last):
4|NexusBot  |   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 79, in wrapped
4|NexusBot  |     ret = await coro(*args, **kwargs)
4|NexusBot  |   File "/home/nexusnation/NexusBot/cogs/CogManager/cogs/leveler/leveler.py", line 292, in profile
4|NexusBot  |     img = await asyncio.wait_for(task, timeout=60)
4|NexusBot  |   File "/usr/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
4|NexusBot  |     return fut.result()
4|NexusBot  |   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
4|NexusBot  |     result = self.fn(*self.args, **self.kwargs)
4|NexusBot  |   File "/home/nexusnation/NexusBot/cogs/CogManager/cogs/leveler/leveler.py", line 217, in make_full_profile
4|NexusBot  |     for line in textwrap.wrap(desc, width=20):
4|NexusBot  |   File "/usr/lib/python3.7/textwrap.py", line 379, in wrap
4|NexusBot  |     return w.wrap(text)
4|NexusBot  |   File "/usr/lib/python3.7/textwrap.py", line 351, in wrap
4|NexusBot  |     chunks = self._split_chunks(text)
4|NexusBot  |   File "/usr/lib/python3.7/textwrap.py", line 337, in _split_chunks
4|NexusBot  |     text = self._munge_whitespace(text)
4|NexusBot  |   File "/usr/lib/python3.7/textwrap.py", line 154, in _munge_whitespace
4|NexusBot  |     text = text.expandtabs(self.tabsize)
4|NexusBot  | AttributeError: 'NoneType' object has no attribute 'expandtabs'
```

**Comment by JamsRepos** [comment]
Found out what it was, it was due to my description being set as none.

**Comment by Malarne** [comment]
that should not be possible as i set it to an empty string on every function ...
