### ISSUE TITLE
League 'accountId'

### ISSUE THREAD

**Issue by 1337god** [Malarne/discord_cogs#62]
```[2020-12-01 21:18:35] [ERROR] red: Exception in command 'history'
Traceback (most recent call last):
  File "/home/X/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/X/.local/share/Red-DiscordBot/data/X/cogs/CogManager/cogs/League/league.py", line 152, in history
    histo = await self.stats.get_history(count, region, summoner)
  File "/home/X/.local/share/Red-DiscordBot/data/X/cogs/CogManager/cogs/League/neeko.py", line 220, in get_history
    sumid = await self.get_account_id(region, summoner)
  File "/home/X/.local/share/Red-DiscordBot/data/X/cogs/CogManager/cogs/League/neeko.py", line 71, in get_account_id
    return js["accountId"]
KeyError: 'accountId'```

How do I set one?

**Comment by Malarne** [comment]
your api key might be wrong or you got ratelimited, unload the cog and wait for a day or two before retrying
